<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ico.ico" />
    <None Remove="images\emoticons\01.png" />
    <None Remove="images\emoticons\02.png" />
    <None Remove="images\emoticons\03.png" />
    <None Remove="images\emoticons\04.png" />
    <None Remove="images\emoticons\05.png" />
    <None Remove="images\emoticons\06.png" />
    <None Remove="images\emoticons\07.png" />
    <None Remove="images\emoticons\08.png" />
    <None Remove="images\emoticons\09.png" />
    <None Remove="images\emoticons\10.png" />
    <None Remove="images\emoticons\11.png" />
    <None Remove="images\emoticons\12.png" />
    <None Remove="images\emoticons\13.png" />
    <None Remove="images\emoticons\14.png" />
    <None Remove="images\emoticons\15.png" />
    <None Remove="images\emoticons\16.png" />
    <None Remove="images\emoticons\17.png" />
    <None Remove="images\emoticons\18.png" />
    <None Remove="SoZvon_logo.ico" />
    <None Remove="SoZvon_logo2.ico" />
    <None Remove="UI\Room_Pages\1742639617_new_bjerxiem4p4b1.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="images\emoticons\15.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\16.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\17.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\18.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="images\app_ico\SoZvon_logo.ico" />
    <Resource Include="images\test_img.jpg" />
    <Content Include="images\emoticons\01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\04.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\05.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\06.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\07.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\08.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\09.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\11.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\13.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\emoticons\14.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="UI\Settings_Pages\SettingsPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UI\Settings_Pages\TitleSettingsPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
